# Linear Regration implementation

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [4]:
from sklearn.datasets import fetch_openml
boston = fetch_openml(name='boston',version=1,as_frame=True,parser='pandas')

In [5]:
boston

{'data':         CRIM    ZN  INDUS CHAS    NOX     RM   AGE     DIS RAD    TAX  \
 0    0.00632  18.0   2.31    0  0.538  6.575  65.2  4.0900   1  296.0
 1    0.02731   0.0   7.07    0  0.469  6.421  78.9  4.9671   2  242.0
 2    0.02729   0.0   7.07    0  0.469  7.185  61.1  4.9671   2  242.0
 3    0.03237   0.0   2.18    0  0.458  6.998  45.8  6.0622   3  222.0
 4    0.06905   0.0   2.18    0  0.458  7.147  54.2  6.0622   3  222.0
 ..       ...   ...    ...  ...    ...    ...   ...     ...  ..    ...
 501  0.06263   0.0  11.93    0  0.573  6.593  69.1  2.4786   1  273.0
 502  0.04527   0.0  11.93    0  0.573  6.120  76.7  2.2875   1  273.0
 503  0.06076   0.0  11.93    0  0.573  6.976  91.0  2.1675   1  273.0
 504  0.10959   0.0  11.93    0  0.573  6.794  89.3  2.3889   1  273.0
 505  0.04741   0.0  11.93    0  0.573  6.030  80.8  2.5050   1  273.0

      PTRATIO       B  LSTAT
 0       15.3  396.90   4.98
 1       17.8  396.90   9.14
 2       17.8  392.83   4.03
 3       18.7  394.63   2.94
 4       18.7  396.90   5.33
 ..       ...     ...    ...
 501     21.0  391.99   9.67
 502     21.0  396.90   9.08
 503     21.0  396.90   5.64
 504     21.0  393.45   6.48
 505     21.0  396.90   7.88

 [506 rows x 13 columns],
 'target': 0      24.0
 1      21.6
 2      34.7
 3      33.4
 4      36.2
        ...
 501    22.4
 502    20.6
 503    23.9
 504    22.0
 505    11.9
 Name: MEDV, Length: 506, dtype: float64,
 'frame':         CRIM    ZN  INDUS CHAS    NOX     RM   AGE     DIS RAD    TAX  \
 0    0.00632  18.0   2.31    0  0.538  6.575  65.2  4.0900   1  296.0
 1    0.02731   0.0   7.07    0  0.469  6.421  78.9  4.9671   2  242.0
 2    0.02729   0.0   7.07    0  0.469  7.185  61.1  4.9671   2  242.0
 3    0.03237   0.0   2.18    0  0.458  6.998  45.8  6.0622   3  222.0
 4    0.06905   0.0   2.18    0  0.458  7.147  54.2  6.0622   3  222.0
 ..       ...   ...    ...  ...    ...    ...   ...     ...  ..    ...
 501  0.06263   0.0  11.93    0  0.573  6.593  69.1  2.4786   1  273.0
 502  0.04527   0.0  11.93    0  0.573  6.120  76.7  2.2875   1  273.0
 503  0.06076   0.0  11.93    0  0.573  6.976  91.0  2.1675   1  273.0
 504  0.10959   0.0  11.93    0  0.573  6.794  89.3  2.3889   1  273.0
 505  0.04741   0.0  11.93    0  0.573  6.030  80.8  2.5050   1  273.0

      PTRATIO       B  LSTAT  MEDV
 0       15.3  396.90   4.98  24.0
 1       17.8  396.90   9.14  21.6
 2       17.8  392.83   4.03  34.7
 3       18.7  394.63   2.94  33.4
 4       18.7  396.90   5.33  36.2
 ..       ...     ...    ...   ...
 501     21.0  391.99   9.67  22.4
 502     21.0  396.90   9.08  20.6
 503     21.0  396.90   5.64  23.9
 504     21.0  393.45   6.48  22.0
 505     21.0  396.90   7.88  11.9

 [506 rows x 14 columns],
 'categories': None,
 'feature_names': ['CRIM',
  'ZN',
  'INDUS',
  'CHAS',
  'NOX',
  'RM',
  'AGE',
  'DIS',
  'RAD',
  'TAX',
  'PTRATIO',
  'B',
  'LSTAT'],
 'target_names': ['MEDV'],
 'DESCR': "**Author**:   \n**Source**: Unknown - Date unknown  \n**Please cite**:   \n\nThe Boston house-price data of Harrison, D. and Rubinfeld, D.L. 'Hedonic\nprices and the demand for clean air', J. Environ. Economics & Management,\nvol.5, 81-102, 1978.   Used in Belsley, Kuh & Welsch, 'Regression diagnostics\n...', Wiley, 1980.   N.B. Various transformations are used in the table on\npages 244-261 of the latter.\nVariables in order:\nCRIM     per capita crime rate by town\nZN       proportion of residential land zoned for lots over 25,000 sq.ft.\nINDUS    proportion of non-retail business acres per town\nCHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\nNOX      nitric oxides concentration (parts per 10 million)\nRM       average number of rooms per dwelling\nAGE      proportion of owner-occupied units built prior to 1940\nDIS      weighted distances to five Boston employment centres\nRAD      index of accessibility to radial highways\nTAX      full-value property-tax rate per $10,000\nPTRATIO  pupil-teacher ratio by town\nB        1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town\nLSTAT    % lower status of the population\nMEDV     Median value of owner-occupied homes in $1000's\n\n\nInformation about the dataset\nCLASSTYPE: numeric\nCLASSINDEX: last\n\nDownloaded from openml.org.",
 'details': {'id': '531',
  'name': 'boston',
  'version': '1',
  'description_version': '1',
  'format': 'ARFF',
  'creator': ['D. and Rubinfeld', "D.L. 'Hedonic"],
  'collection_date': '1978',
  'upload_date': '2014-09-29T00:08:07',
  'language': 'English',
  'licence': 'Public',
  'url': 'https://openml.org/data/v1/download/52643/boston.arff',
  'parquet_url': 'https://data.openml.org/datasets/0000/0531/dataset_531.pq',
  'file_id': '52643',
  'default_target_attribute': 'MEDV',
  'tag': ['Data Science',
   'Housing Economics',
   'Kaggle',
   'OpenML-Reg19',
   'study_130',
   'Urban Studies'],
  'visibility': 'public',
  'status': 'active',
  'processing_date': '2020-11-20 20:16:37',
  'md5_checksum': 'cdd361fb886627eaa80c92f90d0610cc'},
 'url': 'https://www.openml.org/d/531'}

In [6]:
#convert into df
df= boston.frame
df.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [7]:
#create the target column
df['price'] = boston.target
df.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV,price
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2,36.2

In [8]:
#divide the dataset into dependent and independent features

In [9]:
x = df.iloc[:,:-1]
x

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88,11.9

In [10]:
y = df.iloc[:,-1]
y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ...
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: price, Length: 506, dtype: float64

In [11]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score
x = x.astype(float)
y = y.astype(float)

lin_reg = LinearRegression()
mse = cross_val_score(lin_reg,x,y,scoring='neg_mean_squared_error',cv=5)
print(mse)

[-5.22628084e-28 -2.92237818e-28 -1.21219022e-28 -7.15574946e-28
 -1.48417384e-26]

In [12]:
mean_mse = np.mean(mse)
print("mse scores per fold ",mse)

print("Avg negitive mse  ",mean_mse)

mse scores per fold  [-5.22628084e-28 -2.92237818e-28 -1.21219022e-28 -7.15574946e-28
 -1.48417384e-26]
Avg negitive mse   -3.2986796575966365e-27

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)
lin_reg.fit(x_train,y_train)

LinearRegression()

In [14]:
predection = lin_reg.predict(x_test)
predection

array([23.6, 32.4, 13.6, 22.8, 16.1, 20. , 17.8, 14. , 19.6, 16.8, 21.5,
       18.9,  7. , 21.2, 18.5, 29.8, 18.8, 10.2, 50. , 14.1, 25.2, 29.1,
       12.7, 22.4, 14.2, 13.8, 20.3, 14.9, 21.7, 18.3, 23.1, 23.8, 15. ,
       20.8, 19.1, 19.4, 34.7, 19.5, 24.4, 23.4, 19.7, 28.2, 50. , 17.4,
       22.6, 15.1, 13.1, 24.2, 19.9, 24. , 18.9, 35.4, 15.2, 26.5, 43.5,
       21.2, 18.4, 28.5, 23.9, 18.5, 25. , 35.4, 31.5, 20.2, 24.1, 20. ,
       13.1, 24.8, 30.8, 12.7, 20. , 23.7, 10.8, 20.6, 20.8,  5. , 20.1,
       48.5, 10.9,  7. , 20.9, 17.2, 20.9,  9.7, 19.4, 29. , 16.4, 25. ,
       25. , 17.1, 23.2, 10.4, 19.6, 17.2, 27.5, 23. , 50. , 17.9,  9.6,
       17.2, 22.5, 21.4])

In [15]:
#compare a few actual values vs predicted values
comparision_df = pd.DataFrame({'Actual':y_test,'Prdicted':predection})
comparision_df.head()

     Actual  Prdicted
173    23.6      23.6
274    32.4      32.4
491    13.6      13.6
72     22.8      22.8
452    16.1      16.1

In [16]:
from sklearn import metrics
#1 R-Squered socore (best possible score is 1.0)
r2 = metrics.r2_score(y_test,predection)
mae = metrics.mean_absolute_error(y_test,predection)
rmse = np.sqrt(metrics.mean_squared_error(y_test,predection))
print(f"R Square score : {r2:.4f}")
print(f"Mean absolute error : {mae:.4f}")
print(f"Root Mean Square error : {rmse:.4f}")

R Square score : 1.0000
Mean absolute error : 0.0000
Root Mean Square error : 0.0000

# Ridge Regration

In [17]:
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV
ridge = Ridge()

In [18]:
params = {'alpha':[1e-15,1e-10,1e-8,1e-2,1,5,10,20]}
rigdge_regrestion = GridSearchCV(ridge,params,scoring='neg_mean_squared_error',cv=5)
rigdge_regrestion.fit(x,y)

GridSearchCV(cv=5, estimator=Ridge(),
             param_grid={'alpha': [1e-15, 1e-10, 1e-08, 0.01, 1, 5, 10, 20]},
             scoring='neg_mean_squared_error')

In [19]:
print(rigdge_regrestion.best_params_)
print(rigdge_regrestion.best_score_)

{'alpha': 1e-15}
-1.0724786222976156e-27

# Lasso Regression

In [20]:
from sklearn.linear_model import Lasso
from sklearn.model_selection import GridSearchCV
lasso = Lasso()
params = {'alpha':[1e-15,1e-10,1e-8,1e-2,1,5,10,20]}
lasso_regrestion = GridSearchCV(lasso,params,scoring='neg_mean_squared_error',cv=5)
lasso_regrestion.fit(x,y)

GridSearchCV(cv=5, estimator=Lasso(),
             param_grid={'alpha': [1e-15, 1e-10, 1e-08, 0.01, 1, 5, 10, 20]},
             scoring='neg_mean_squared_error')

In [21]:
print(lasso_regrestion.best_params_)
print(lasso_regrestion.best_score_)

{'alpha': 1e-08}
-1.0626085889419073e-07

In [22]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score
# Ensure data is numeric
x = x.astype(float)
y = y.astype(float)
# scale the feature for (Essentials for Ridge and lasoo)
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)
x_train,x_test,y_train,y_test = train_test_split(x_scaled,y,test_size=0.2,random_state=42)

# Linear Regression

In [23]:
from sklearn.linear_model import LinearRegression
#intlize and train
lin_reg = LinearRegression()
lin_reg.fit(x_train,y_train)
# predirect and calculate accurancy
lin_pred = lin_reg.predict(x_test)
lin_acc = r2_score(y_test,lin_pred)*100
print(f"Linear Regrestion Accuracy: {lin_acc:.2f}%")

Linear Regrestion Accuracy: 100.00%

# Ridge Regression

In [24]:
from sklearn.linear_model import Ridge
ridge_reg = Ridge(alpha=10.0)
ridge_reg.fit(x_train,y_train)

#predict and calculate accurracy
ridge_pred = ridge_reg.predict(x_test)
ridge_acc = r2_score(y_test,ridge_pred)*100
print(f"Ridge Regression Accuracy : {ridge_acc:.2f}%")

Ridge Regression Accuracy : 99.76%