In [9]:
import pandas as pd
data = {'color':['red','blue','orange','black','Yellow']}
df = pd.DataFrame(data)
df

    color
0     red
1    blue
2  orange
3   black
4  Yellow

In [10]:
#Perfoming one-hot encoding 
one_hot_encoding = pd.get_dummies(df['color'],prefix='color')
one_hot_encoding

   color_Yellow  color_black  color_blue  color_orange  color_red
0         False        False       False         False       True
1         False        False        True         False      False
2         False        False       False          True      False
3         False         True       False         False      False
4          True        False       False         False      False

In [11]:
#combinig the enconded data with original data
df = pd.concat([df,one_hot_encoding],axis=1)
df

    color  color_Yellow  color_black  color_blue  color_orange  color_red
0     red         False        False       False         False       True
1    blue         False        False        True         False      False
2  orange         False        False       False          True      False
3   black         False         True       False         False      False
4  Yellow          True        False       False         False      False

In [12]:
df = df.drop('color',axis=1)
df

   color_Yellow  color_black  color_blue  color_orange  color_red
0         False        False       False         False       True
1         False        False        True         False      False
2         False        False       False          True      False
3         False         True       False         False      False
4          True        False       False         False      False